Add web application testing workflow

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -1,39 +1,136 @@
 name: 'WebApp Console Log Action'
-description: 'Runs a web application in a browser, waits a few seconds, and posts console logs as a comment to the PR.'
-author: 'Jannis Hell'
+description: 'An action to capture and post console logs from a web application'
+author: 'Jannis Hell (@Primajin)'
+branding:
+  icon: 'clipboard'
+  color: 'blue'
 inputs:
   webapp-url:
-    description: 'The URL of the web application to test'
+    description: 'The URL of the web application'
     required: true
   wait-time:
-    description: 'Time in milliseconds to wait before capturing console logs'
+    description: 'The wait time before capturing logs'
     required: false
-    default: 5000
+    default: 2500
+  show-emoji:
+    description: 'Whether to show emojis in the output'
+    required: false
+    default: true
+  min-log-level:
+    description: 'The minimum log level to capture (verbose, info, warning, error)'
+    required: false
+    default: 'verbose'
+  max-log-level:
+    description: 'The maximum log level to allow (verbose, info, warning, error). Set to error to disable failing.'
+    required: false
+    default: 'info'
+  comment-tag:
+    description: 'The tag to use for the comment - so it can be replaced, you may pass empty string to always post a new comment'
+    required: false
+    default: 'console-log'
+  headline:
+    description: 'The headline for the console logs comment'
+    required: false
+    default: 'Console Logs'
 outputs:
   console-log:
     description: 'The captured console log'
 runs:
   using: 'composite'
   steps:
-    - name: Set up Node.js
-      uses: actions/setup-node@v2
+    - name: Checkout Code
+      uses: actions/checkout@v4
+
+    - name: Setup Node.js
+      uses: actions/setup-node@v4
       with:
-        node-version: '14'
-    - name: Install dependencies
-      run: npm install
-    - name: Run Chromium and capture console logs
+        node-version: '22'
+        cache: 'npm'
+
+    - name: Cache Dependencies
+      uses: actions/cache@v4
+      with:
+        path: ~/.npm
+        key: npm-${{ hashFiles('package-lock.json') }}
+        restore-keys: |
+          npm-${{ hashFiles('package-lock.json') }}
+          npm-
+
+    - name: Install Dependencies
+      run: npm ci
+      shell: bash
+
+    - name: Run Chromium and Capture Console Logs
       uses: browser-actions/setup-chromium@v1
-    - run: |
+
+    - name: Execute Capture Script
+      run: |
         npx playwright install chromium
-        node .github/scripts/capture-console.js
+        node capture-console.js
       env:
         WEBAPP_URL: ${{ inputs.webapp-url }}
         WAIT_TIME: ${{ inputs.wait-time }}
-    - name: Post console output to PR
+        MIN_LOG_LEVEL: ${{ inputs.min-log-level }}
+        MAX_LOG_LEVEL: ${{ inputs.max-log-level }}
+      shell: bash
+
+    - name: Set Output
+      id: capture-console
+      run: |
+        echo 'console<<EOF' >> $GITHUB_OUTPUT
+        echo $(cat console_output.json) >> $GITHUB_OUTPUT
+        echo 'EOF' >> $GITHUB_OUTPUT
+      shell: bash
+
+    - name: Format Console Output  # Step to format the console output into GitHub Flavored Markdown
+      id: format_console_output
+      run: |
+        # Create a markdown file and add a main heading
+        echo "# ${{ inputs.headline }}" > formatted_console_output.md
+        # Loop through each key in the JSON file
+        for key in $(jq -r 'keys[]' console_output.json); do
+          # Capitalize the first character of the key
+          capitalized_key=$(echo "$key" | awk '{print toupper(substr($0, 1, 1)) tolower(substr($0, 2))}')
+          # Add a subheading for each log level with matching emoji if show-emoji is true
+          if [ "${{ inputs.show-emoji }}" = "true" ]; then
+            case "$key" in
+              verbose) emoji="💬" ;;
+              info) emoji="ℹ️" ;;
+              warning) emoji="⚠️" ;;
+              error) emoji="❌" ;;
+              *) emoji="" ;;
+            esac
+            echo "## $emoji $capitalized_key" >> formatted_console_output.md
+          else
+            echo "## $capitalized_key" >> formatted_console_output.md
+          fi
+          # Add a code block for each log message
+          echo '```' >> formatted_console_output.md
+          # Add each log message
+          jq -r --arg key "$key" '.[$key][]' console_output.json >> formatted_console_output.md
+          # Close the code block
+          echo '```' >> formatted_console_output.md
+          # Add an empty line for better readability when editing
+          echo "" >> formatted_console_output.md
+        done
+      shell: bash
+
+    - name: Post Console Output to PR
       if: github.event_name == 'pull_request'
+      uses: thollander/actions-comment-pull-request@v3
+      with:
+        comment-tag: ${{ inputs.comment-tag }}
+        file-path: formatted_console_output.md
       env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      run: node .github/scripts/post-comment.js
-branding:
-  icon: 'clipboard'
-  color: 'blue'
+        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
+
+    - name: Check if action should fail
+      run: |
+        if [ "$SHOULD_FAIL_ACTION" = "true" ]; then
+          echo "Action should fail due to log level threshold."
+          exit 1
+        fi
+      shell: bash
+      env:
+        SHOULD_FAIL_ACTION: ${{ env.SHOULD_FAIL_ACTION }}
+
